# route testing with REST Client extension in VS Code.

###


GET http://localhost:3001/api/categories

###


GET http://localhost:3001/api/products

###


GET http://localhost:3001/api/tags

###


POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "category_name": "Movies"
}

###

POST http://localhost:3001/api/products
Content-Type: application/json

{
    "product_name": "Basketball",
    "price": 200.00,
    "stock": 3,
    "tagIds": [1, 2, 3, 4]
}

###


POST http://localhost:3001/api/tags
Content-Type: application/json

{
    "tag_name": "wearable",
    "productIds": [1,2,3]

}

###


GET http://localhost:3001/api/categories/9

###


GET http://localhost:3001/api/products/7

###


GET http://localhost:3001/api/tags/3

###



PUT http://localhost:3001/api/categories/9
Content-Type: application/json

{
    "category_name":"Toys"
}


###


PUT http://localhost:3001/api/products/7
Content-Type: application/json

{
    "category_id" : 6,
    "stock" : 10,
    "price" : 12,
    "tagIds" : [10]
}

###


PUT http://localhost:3001/api/tags/:id

###


DELETE  http://localhost:3001/api/categories/:id

###


DELETE  http://localhost:3001/api/products/:id

###


DELETE  http://localhost:3001/api/tags/:id

###