# route testing with REST Client extension in VS Code.

###


GET http://localhost:3001/api/categories

###


GET http://localhost:3001/api/products

###


GET http://localhost:3001/api/tags

###


POST http://localhost:3001/api/categorie

###


POST http://localhost:3001/api/products

###


POST http://localhost:3001/api/tags

###


GET http://localhost:3001/api/categories/:id

###


GET http://localhost:3001/api/products/:id

###


GET http://localhost:3001/api/tags/:id

###


POST http://localhost:3001/api/categories

###


POST http://localhost:3001/api/products/

###


POST http://localhost:3001/api/tags/

###


PUT http://localhost:3001/api/categories/:id

###


PUT http://localhost:3001/api/products/:id

###


PUT http://localhost:3001/api/tags/:id

###


DELETE  http://localhost:3001/api/categories/:id

###


DELETE  http://localhost:3001/api/products/:id

###


DELETE  http://localhost:3001/api/tags/:id

###