# route testing with REST Client extension in VS Code.

###


GET http://localhost:3001/api/categories

###


GET http://localhost:3001/api/products

###


GET http://localhost:3001/api/tags

###


POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "category_name": "Movies"
}

###

POST http://localhost:3001/api/products
Content-Type: application/json

{
    "product_name": "Basketball",
    "price": 200.00,
    "stock": 3,
    "tagIds": [1, 2, 3, 4]
}

###


POST http://localhost:3001/api/tags
Content-Type: application/json

{
    "tag_name": "wearable",
    "productIds": [1,2,3]

}

###


GET http://localhost:3001/api/categories/1

###


GET http://localhost:3001/api/products/2

###


GET http://localhost:3001/api/tags/3

###



PUT http://localhost:3001/api/categories/:id

###


PUT http://localhost:3001/api/products/:id

###


PUT http://localhost:3001/api/tags/:id

###


DELETE  http://localhost:3001/api/categories/:id

###


DELETE  http://localhost:3001/api/products/:id

###


DELETE  http://localhost:3001/api/tags/:id

###